services:
  app:
    build:
      context: .
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - MEILI_URL=http://meilisearch:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - NEXT_PUBLIC_MAPTILER_KEY=${NEXT_PUBLIC_MAPTILER_KEY}
    depends_on:
      meilisearch:
        condition: service_healthy
    restart: unless-stopped

  meilisearch:
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_ENV=production
    restart: unless-stopped
